###
#
# A set of Make targets, variables, etc. that are generally useful.
# No need for autoconf! (maybe)
#
###

include $(MAKEMAGIC_DIR)makemagic/os_detection.mk
include $(MAKEMAGIC_DIR)makemagic/dir_functions.mk
include $(MAKEMAGIC_DIR)makemagic/prerequisite_functions.mk
include $(MAKEMAGIC_DIR)makemagic/web_functions.mk